#!/bin/bash

# Cloudflare Tunnel Setup Guide for FarmPro.Tech
# ================================================

echo "🚀 Cloudflare Tunnel Setup Complete!"
echo ""
echo "📝 IMPORTANT: Update Your Cloudflare DNS Records"
echo "================================================"
echo ""
echo "Go to Cloudflare Dashboard → DNS → Records"
echo ""
echo "DELETE the following A records:"
echo "  ❌ A record: @ (farmpro.tech) → 129.107.192.138"
echo "  ❌ A record: farmpro.tech → 129.107.192.138"
echo "  ❌ A record: www → 129.107.192.138"
echo ""
echo "ADD these CNAME records instead:"
echo "  ✅ Type: CNAME"
echo "     Name: farmpro.tech (or @)"
echo "     Target: 54026a12-80a9-4414-b0a0-d1cb39d69dbc.cfargotunnel.com"
echo "     Proxy: Enabled (Orange Cloud)"
echo ""
echo "  ✅ Type: CNAME"
echo "     Name: www"
echo "     Target: 54026a12-80a9-4414-b0a0-d1cb39d69dbc.cfargotunnel.com"
echo "     Proxy: Enabled (Orange Cloud)"
echo ""
echo "================================================"
echo ""
echo "After updating DNS, run the tunnel with:"
echo "  cloudflared tunnel run farmpro"
echo ""
echo "Or install as a service to run automatically:"
echo "  sudo cloudflared service install"
echo ""
